"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import environ
from pathlib import Path
from datetime import timedelta
import sys

#from pathlib import Path 
#import os 
import dj_database_url 
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis de ambiente do arquivo .env 
load_dotenv(BASE_DIR / ".env")


# Inicializar django-environ
env = environ.Env(
    DEBUG=(bool, False) # Valor padrão caso não esteja no .env
)
# Ler o arquivo .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = env('SECRET_KEY')
# Lê do ambiente. Se não achar, usa uma chave insegura (fallback) 
SECRET_KEY = os.getenv("SECRET_KEY", "chave-insegura-fallback")

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
#DEBUG = env('DEBUG')
# Lê do ambiente. Retorna 'True' se o valor for "True", senão False. 
DEBUG = os.getenv("DEBUG", "False") == "True"

#ALLOWED_HOSTS = []
# Hosts permitidos 
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
# O Render define a variável RENDER_EXTERNAL_HOSTNAME automaticamente 
render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME") 
if render_host: 
    ALLOWED_HOSTS.append(render_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    # Local apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware", # <--- ADICIONE AQUI
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''
DATABASES = { 
    "default": dj_database_url.config( 
        default=os.getenv("DATABASE_URL"), 
        conn_max_age=600, 
        ssl_require=True, # Importante para Render 
        ) 
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
# Compactação e cacheamento otimizado 
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuração do Django REST Framework 
REST_FRAMEWORK = { 
    'DEFAULT_AUTHENTICATION_CLASSES': (
         # Define JWT como método de autenticação PADRÃO 
         'rest_framework_simplejwt.authentication.JWTAuthentication', 
         ), 
         # Outras configurações padrão 
         }
# Configuração do Simple JWT 
SIMPLE_JWT = { 
    # Tempo de vida do Access Token (curto!) 
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), 
    # Tempo de vida do Refresh Token (longo!) 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), 
    # Define o esquema de autenticação no header HTTP 
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Algoritmo de criptografia 
    'ALGORITHM': 'HS256', 
    # Nome do campo de usuário no payload (user_id é padrão) 
    'USER_ID_CLAIM': 'user_id', 
    }

# Configuração para acelerar testes 
# # Se o comando 'test' estiver sendo executado, 
# trocamos o banco para SQLite em memória 
if 'test' in sys.argv: 
    DATABASES['default'] = {
         'ENGINE': 'django.db.backends.sqlite3', 
         'NAME': ':memory:', # Banco reside apenas na RAM
    }